### ISSUE TITLE
Linter error: Missing html/text field on Linter Response

### ISSUE THREAD

**Issue by cblp** [atom-haskell/haskell-ghc-mod#124]
When switch on "Use Linter" option, I get only
```
Error: Missing html/text field on Linter Response
    at ~/.atom/packages/linter/lib/validate.coffee:40:19
    at Array.forEach (native)
    at Object.module.exports.Validate.messages (~/.atom/packages/linter/lib/validate.coffee:27:14)
    at MessageRegistry.set (~/.atom/packages/linter/lib/message-registry.js:36:16)
    at ~/.atom/packages/linter/lib/linter.coffee:37:17
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ~/.atom/packages/linter/lib/linter-registry.js:66:26
    at process._tickCallback (node.js:368:9)
```
atom 1.5.3
```
haskell-ghc-mod@1.10.1
ide-haskell@1.5.3
ide-haskell-stack@0.0.3
language-haskell@1.7.2
linter@1.11.3
linter-hlint@0.4.3
linter-pylint@1.2.0
```

**Comment by lierdakil** [comment]
Can't reproduce. Does it happen on everything?

**Comment by cblp** [comment]
I updated haskell-ghc-mod plugin, now this problem has gone.

**Comment by lierdakil** [comment]
Probably compilation error. Usually reinstalling package helps in these cases.
