### ISSUE TITLE
Failed to activate the haskell-ghc-mod package

### ISSUE THREAD

**Issue by c200chromebook** [atom-haskell/haskell-ghc-mod#143]
[Enter steps to reproduce below:]

1. Open any haskell file.
2. Get this error.

**Atom Version**: 1.7.3
**System**: Ubuntu 12.04.5
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.12.3

### Stack Trace

Failed to activate the haskell-ghc-mod package

```
At stackpath.split is not a function

TypeError: stackpath.split is not a function
    at Object.module.exports.Util.getProcessOptions (/home/mdw/.atom/packages/haskell-ghc-mod/lib/util.coffee:108:27)
    at GhcModiProcess.module.exports.GhcModiProcess.getVersion (/home/mdw/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:53:17)
    at new GhcModiProcess (/home/mdw/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:24:8)
    at Object.module.exports.HaskellGhcMod.activate (/home/mdw/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:112:16)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:841:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app.asar/src/package-manager.js:561:36)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:501:17
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-elm"
    ]
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.5
haskell-ghc-mod, v1.12.3
ide-haskell, v1.6.3
ide-haskell-cabal, v1.3.2
ide-haskell-repl, v0.0.21
language-haskell, v1.7.15

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Should be fixed by 1.12.4. Let me know if not.

**Comment by jasonkuhrt** [comment]
I just got this error upon creating and opening a new Haskell file.

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.18.0


### Stack Trace

Failed to activate the haskell-ghc-mod package

```
At Cannot find module './ghc-mod/ghc-modi-process'

Error: Cannot find module './ghc-mod/ghc-modi-process'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.module.exports.HaskellGhcMod.activate (/Users/jasonkuhrt/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:137:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:847:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:573:43)
    at Workspace.module.exports.Workspace.handleGrammarUsed (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:619:34)
    at TextEditor.module.exports.TextEditor.observeGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:570:7)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:265:189
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:491:20)
    at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:434:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:546:18
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

### Commands

```
     -1:28.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  6x -1:27.2.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:20.5.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:20.4.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -1:19.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:13.5.0 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:13.4.0 vim-mode:bracket-matching-motion (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:12.6.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:12.4.0 core:close (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:11.4.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nucleus-dark-ui.ide-haskell)
     -1:10.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:10.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:10 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nucleus-dark-ui.ide-haskell)
     -0:59.7.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nucleus-dark-ui.ide-haskell)
     -0:03.6.0 core:close (div.panels-item)
     -0:01.4.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-fusion-syntax.theme-nucleus-dark-ui.ide-haskell)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "mocha-test-runner",
      "Clean",
      "ide-haskell-hasktags",
      "linter-hlint",
      "linter-flow",
      "project-manager"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "onChangeCheck": true,
    "onChangeLint": true,
    "onMouseHoverShow": "info",
    "onSelectionShow": "typeInfo",
    "showTypeOnSelection": true,
    "useLinter": true
  }
}
```

### Installed Packages

```coffee
# User
adventurous-syntax, v0.2.0 (inactive)
asciidoc-preview, v2.6.0 (active)
atom-dark-fusion-syntax, v1.2.4 (active)
atomatigit, v1.5.5 (active)
autocomplete-haskell, v0.6.7 (active)
autosave, v0.23.2 (active)
color-picker, v2.2.2 (active)
gist-it, v0.9.1 (inactive)
gruvbox, v1.0.5 (inactive)
haskell-ghc-mod, v1.18.0 (active)
ide-haskell, v1.8.1 (active)
ide-haskell-cabal, v1.6.4 (active)
ide-haskell-hasktags, v0.0.7 (inactive)
ide-haskell-repl, v0.1.10 (active)
language-asciidoc, v1.5.1 (active)
language-diff, v0.6.0 (active)
language-docker, v1.1.7 (active)
language-elm, v1.5.0 (active)
language-haskell, v1.9.9 (active)
language-jade, v0.7.2 (active)
language-protobuf, v0.7.0 (active)
language-purescript, v0.8.2 (active)
language-terraform, v0.7.4 (active)
linter, v1.11.18 (active)
linter-coffeelint, v1.1.2 (active)
linter-eslint, v8.0.0 (active)
linter-flow, v5.5.0 (inactive)
linter-hlint, v0.5.0 (inactive)
nucleus-dark-ui, v0.10.11 (active)
project-manager, v3.2.5 (inactive)
react, v0.16.1 (active)
seti-syntax, v1.0.1 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
vim-mode, v0.65.1 (active)
wordcount, v2.7.0 (active)
Zen, v0.16.4 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
@jasonkuhrt, it's different. From stacktrace, I would guess that either Atom's compilation cache got corrupted for some reason, or haskell-ghc-mod package got borked during or after installation. In any case, try to reinstall it.

**Comment by jasonkuhrt** [comment]
I haven't seen this issue for a while. If it happens again I'll try to give more info.
