### ISSUE TITLE
Haskell-ghc-mod: ghc-mod command list failed with error code 1

### ISSUE THREAD

**Issue by stephenoken** [atom-haskell/haskell-ghc-mod#144]
**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.13.1

### Stack Trace

Haskell-ghc-mod: ghc-mod command list failed with error code 1

```
At caps: {"version":[5,5,0,0],"fileMap":true,"quoteArgs":true,"optparse":true,"typeConstraints":false,"browseParents":false,"interactiveCaseSplit":false}
URI: undefined
Args: --
message: Warning: /Users/stephenokennedy/.cabal/config: Unrecognized field ghc-options
on line 176

cabal: At least the following dependencies are missing:

distributed-process -any, network-transport-tcp -any

ghc-mod: readCreateProcess: cabal "configure" "--with-ghc=ghc" "--flags" "" (exit 1): failed

log:
-1.364s: running ghc-mod list,-- with options.cwd = /Users/stephenokennedy/Development/haskell/cloud-haskell/map-reduce,options.env = [object Object],options.encoding = utf-8
-1.281s: ghc-mod said: Warning: /Users/stephenokennedy/.cabal/config: Unrecognized field ghc-options
-1.281s: ghc-mod said: on line 176
-0.009s: ghc-mod said: cabal: At least the following dependencies are missing:
-0.009s: ghc-mod said: distributed-process -any, network-transport-tcp -any
-0.004s: ghc-mod said: ghc-mod: readCreateProcess: cabal "configure" "--with-ghc=ghc" "--flags" "" (exit 1): failed
-0.001s: ghc-mod ended with code 1
-0.001s: code 1: Warning: /Users/stephenokennedy/.cabal/config: Unrecognized field ghc-options
on line 176

cabal: At least the following dependencies are missing:

distributed-process -any, network-transport-tcp -any

ghc-mod: readCreateProcess: cabal "configure" "--with-ghc=ghc" "--flags" "" (exit 1): failed


code 1: Warning: /Users/stephenokennedy/.cabal/config: Unrecognized field ghc-options
on line 176

cabal: At least the following dependencies are missing:

distributed-process -any, network-transport-tcp -any

ghc-mod: readCreateProcess: cabal "configure" "--with-ghc=ghc" "--flags" "" (exit 1): failed

    at module.exports.Util.mkError (/Users/stephenokennedy/.atom/packages/haskell-ghc-mod/lib/util.coffee:212:15)
    at BufferedProcess.exit (/Users/stephenokennedy/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.coffee:101:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -6:41.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -6:40.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:40.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:40.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -6:39.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:38.7.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -6:38.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -6:37.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -6:37.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -6:37.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -6:37.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -6:34.2.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -6:33.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:29.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:18.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:02.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-html",
      "language-groovy",
      "go-config",
      "go-get"
    ]
  },
  "haskell-ghc-mod": {
    "additionalPathDirectories": [
      "/usr/local/bin"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-ternjs, v0.14.1
autocomplete-haskell, v0.6.5
autocomplete-modules, v1.4.1
autocomplete-python, v1.7.2
environment, v1.2.0
file-icons, v1.7.11
hashrocket, v0.4.10
haskell-ghc-mod, v1.13.1
ide-haskell, v1.6.3
ide-haskell-cabal, v1.3.3
ide-haskell-stack, v0.0.3
language-ejs, v0.2.0
language-haskell, v1.7.15
language-lisp, v0.2.0
linter, v1.11.4
linter-eslint, v7.2.2
linter-ruby, v1.2.2
minimap, v4.23.5
minimap-git-diff, v4.3.1
navigator-godef, v1.0.3
node-debugger, v1.7.0
python-tools, v0.6.7
react, v0.15.0
terminal-panel, v1.14.1
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by stephenoken** [comment]
Sorry, I was being an idiot making this issue. I'm new to haskell, stack and cabal. Managed to fix the error by running `cabal install`.

**Comment by lierdakil** [comment]
No problem, it's what 'create issue' button is for.

A couple tips:
- If using cabal, *use sandboxes* (`cabal sandbox init` in project root) -- globally installing packages will lead to much grief later, when you want to update something.
- You can use `cabal install --only-dependencies` to install, you guessed it, only dependencies, and not the package itself. In most cases, you don't want to install package you're working on at the moment.
- Prefer stack to cabal-install if you can. Stack is much friendlier to beginners for the most part, provided you don't try to mix resolvers.

**Comment by stephenoken** [comment]
Cheers!! I'll keep those tips in mind.
