### ISSUE TITLE
Getting this issue, while configuring ATOM with Haskell

### ISSUE THREAD

**Issue by RohithKumar** [atom-haskell/haskell-ghc-mod#163]
**Issue1:** 
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. ENOENT
Error: spawn ghc-mod ENOENT
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
path: undefined
Path: undefined
Hide Stack Trace
Error
    at /home/maximus/.atom/packages/haskell-ghc-mod/lib/util.coffee:60:26
    at exithandler (child_process.js:232:5)
    at ChildProcess.errorhandler (child_process.js:244:5)
    at emitOne (events.js:77:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
The error was thrown from the haskell-ghc-mod package.

**Issue 2:**

Failed to spawn command hasktags. Make sure hasktags is installed and on your PATH

**Comment by lierdakil** [comment]
1) Did you install ghc-mod? See https://github.com/atom-haskell/ide-haskell#requirements
2) You need to add directory that contains ghc-mod executable (i.e. `ghc-mod` binary) to 'Additional Path Directories' setting. Again, see link above.
3) Pretty much the same goes for hasktags, but it relates to `ide-haskell-hasktags` package, and you will want to set 'hasktags path' setting to `/path/to/binary/hasktags` (e.g. `/home/user/.cabal/bin/hasktags`)

**Comment by lierdakil** [comment]
Closing due to inactivity
