### ISSUE TITLE
Failed to activate the haskell-ghc-mod package

### ISSUE THREAD

**Issue by brsunter** [atom-haskell/haskell-ghc-mod#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.6.3

### Stack Trace

Failed to activate the haskell-ghc-mod package

```
At Invalid value used as weak map key

TypeError: Invalid value used as weak map key
    at WeakMap.has (native)
    at CompletionBackend.module.exports.CompletionBackend.getModuleMap (/Users/briansunter/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:357:24)
    at CompletionBackend.module.exports.CompletionBackend.registerCompletionBuffer (/Users/briansunter/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:474:20)
    at CompletionBackend.registerCompletionBuffer (/Users/briansunter/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:3:61)
    at /Users/briansunter/.atom/packages/autocomplete-haskell/lib/autocomplete-haskell.coffee:66:54
    at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
    at Object.module.exports.AutocompleteHaskell.consumeCompBack_0_1_0 (/Users/briansunter/.atom/packages/autocomplete-haskell/lib/autocomplete-haskell.coffee:61:50)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:34)
    at ServiceHub.module.exports.ServiceHub.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:29:18)
    at Package.module.exports.Package.activateServices (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:372:65)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "haskell-ghc-mod": {
    "ghcModPath": "/Users/briansunter/.cabal/bin//ghc-mod",
    "ghcModiPath": "/Users/briansunter/.cabal/bin//ghc-modi"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.3
haskell-ghc-mod, v0.6.3
ide-haskell, v0.5.7
language-haskell, v1.0.0
linter-hlint, v0.3.6
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
This is related to #18, so I'll reopen.

**Comment by brsunter** [comment]
@lierdakil Feel free to close this one, it's a duplicate, I was using an odd path (    "ghcModPath": "/Users/briansunter/.cabal/bin//ghc-mod",) and reopened one using a normal path (/Users/briansunter/.cabal/bin/ghc-mod)

**Comment by lierdakil** [comment]
Ok, if you say so.

**Comment by harcharansidhu** [comment]
I am getting the following error:

Failed to activate the haskell-ghc-mod package
Error: spawnSync ghc-mod ENOENT

I get this every time I open atom.

**Comment by lierdakil** [comment]
@harcharansidhu, set the package up. It can't find `ghc-mod` executable.

**Comment by harcharansidhu** [comment]
Sorry not sure what you mean by 'setting up the package'.

I have tried to update it an I got the following error report:

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.2.7


### Stack Trace

Failed to activate the haskell-ghc-mod package

```
At spawnSync ghc-mod ENOENT

Error: spawnSync ghc-mod ENOENT
    at exports._errnoException (util.js:837:11)
    at Object.spawnSync (child_process.js:432:20)
    at new GhcModiProcess (/Users/harcharansidhu/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:24:14)
    at Object.module.exports.HaskellGhcMod.activate (/Users/harcharansidhu/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:83:16)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:385:60
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -1:17.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-seti-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-haskell, v0.6.2
autocomplete-python, v1.2.4
color-picker, v2.0.14
haskell-ghc-mod, v1.2.7
haskell-pointfree, v0.1.2
highlight-selected, v0.11.1
ide-haskell, v1.3.7
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.10
language-haskell, v1.5.1
language-oz, v0.1.0
linter, v1.11.3
linter-pylint, v1.2.0
minimap, v4.19.0
seti-ui, v0.8.1
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
1.2.7 should've caught that... nevermind. Please read this: https://github.com/atom-haskell/haskell-ghc-mod#configuration

**Comment by harcharansidhu** [comment]
I tried to but:

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.2.7


### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured.

Restart Atom after configuring.

```
At Error: spawnSync Users/harcharansidhu/Library/Haskell/ghc-7.10.2-x86_64/lib/ghc-mod-5.4.0.0 EACCES

Error: spawnSync Users/harcharansidhu/Library/Haskell/ghc-7.10.2-x86_64/lib/ghc-mod-5.4.0.0 EACCES
    at exports._errnoException (util.js:837:11)
    at Object.spawnSync (child_process.js:432:20)
    at new GhcModiProcess (/Users/harcharansidhu/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:24:14)
    at Object.module.exports.HaskellGhcMod.activate (/Users/harcharansidhu/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:84:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "Users/harcharansidhu/Library/Haskell/ghc-7.10.2-x86_64/lib/ghc-mod-5.4.0.0",
    "additionalPathDirectories": [
      "/Users/harcharansidhu/Library/Haskell/bin"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.19.0
autocomplete-python, v1.2.4
color-picker, v2.0.14
haskell-ghc-mod, v1.2.7
haskell-pointfree, v0.1.2
highlight-selected, v0.11.1
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.1
language-oz, v0.1.0
linter, v1.11.3
linter-pylint, v1.2.0
minimap, v4.19.0
seti-ui, v0.8.1
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
You need to specify path to executable file itself, not just a directory
that contains it. Also you apparently missed first slash.
28 Дек 2015 г. 0:44 пользователь "Harcharan Sidhu" <notifications@github.com>
написал:

**Comment by harcharansidhu** [comment]
thank you.
