### ISSUE TITLE
ghc-modi crashed

### ISSUE THREAD

**Issue by peteryhwong** [atom-haskell/haskell-ghc-mod#181]
```
ghc-modi crashed
    at module.exports.Util.mkError (/Users/wongpet/.atom/packages/haskell-ghc-mod/lib/util.coffee:225:15)
    at ChildProcess.exitCallback (/Users/wongpet/.atom/packages/haskell-ghc-mod/lib/ghc-mod/interactive-process.coffee:77:20)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by peteryhwong** [comment]
I am running `ghc-mod version 5.5.0.0 compiled by GHC 7.10.3`

**Comment by lierdakil** [comment]
You will have to post full log, I can't diagnose ghc-mod crash based on Atom's stacktrace.

![atom-report](https://cloud.githubusercontent.com/assets/7275622/19223878/e8ea4d72-8e82-11e6-9857-abc20486f4f3.png) then paste clipboard contents here. If you have privacy concerns related to your project internals, send that to my e-mail instead (see github profile).
