### ISSUE TITLE
SQLite Error, running stack in docker

### ISSUE THREAD

**Issue by PiMaker** [atom-haskell/haskell-ghc-mod#200]
As mentioned in #145, ghc-mod in atom crashes everytime it runs (on save). The error is "SQLite3 returned ErrorBusy while attempting to perform step.\n"

I am running ghc-mod in stack, using a custom wrapper script to perform that step. I know this is a weird setup, but everything works perfectly except for ghc-mod in Atom.

```
**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Ubuntu 16.04
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.19.4


### Stack Trace

Haskell-ghc-mod: ghc-mod command browse failed with error Error

At caps: {"version":[5,6,0,0],"fileMap":true,"quoteArgs":true,"optparse":true,"typeConstraints":true,"browseParents":true,"interactiveCaseSplit":true,"importedFrom":false}
URI: undefined
Args: -d,-p,--,Main
message: Command failed: ghc-mod browse -d -p -- Main
SQLite3 returned ErrorBusy while attempting to perform step.

log:
-0.083s: "Main did-save triggered"
-0.083s: "Main updating"
-0.069s: "Running ghc-mod check,/home/pi/Repos/PayrollSingle/PayrollCalculation/src/Main.hs,-- with opts = "..."
-0.001s: "SQLite3 returned ErrorBusy while attempting to perform step.\n"
-0.001s: "Running ghc-mod browse,-d,-p,--,Main failed with ",{"killed":false,"code":1,"signal":null,"cmd":"ghc-mod browse -d -p -- Main"}
0s: {"killed":false,"code":1,"signal":null,"cmd":"ghc-mod browse -d -p -- Main"}

Error
    at /home/pi/.atom/packages/haskell-ghc-mod/lib/util.coffee:60:26
    at ChildProcess.exithandler (child_process.js:221:5)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)

### Commands

     -0:12.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.1.0 core:save (atom-text-editor.editor.is-focused)

### Config

json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ]
  },
  "haskell-ghc-mod": {
    "additionalPathDirectories": [
      "./atom-bin"
    ],
    "cabalSandbox": false,
    "enableGhcModi": false,
    "onSaveLint": false,
    "stackSandbox": false
  }
}

### Installed Packages

coffee
# User
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.17 (active)
atom-pair, v2.0.10 (active)
autocomplete-go, v1.1.1 (active)
autocomplete-haskell, v0.6.7 (active)
autocomplete-java, v1.2.5 (inactive)
builder-go, v1.0.1 (active)
file-icons, v1.7.25 (active)
go-config, v1.2.3 (active)
go-get, v1.0.4 (active)
go-plus, v5.0.9 (inactive)
godoc, v0.4.0 (active)
gofmt, v1.1.8 (active)
gometalinter-linter, v1.1.1 (active)
gorename, v1.0.3 (active)
haskell-ghc-mod, v1.19.4 (active)
haskell-pointfree, v0.1.3 (active)
ide-haskell, v1.8.2 (active)
ide-haskell-repl, v0.5.0 (active)
java-generator, v2.2.3 (inactive)
java-importer, v1.4.1 (active)
language-docker, v1.1.7 (active)
language-haskell, v1.12.1 (active)
language-markdown, v0.19.1 (active)
linter, v1.11.18 (active)
linter-javac, v1.9.4 (active)
navigator-godef, v1.0.4 (active)
script, v3.14.1 (inactive)
term3, v0.22.1 (active)
tester-go, v1.0.6 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages

```

**Comment by lierdakil** [comment]
Try enabling 'Low Memory System' in haskell-ghc-mod settings. This will force single-threaded operation, which in theory might help. Also, your Atom version is kinda outdated.

**Comment by PiMaker** [comment]
Thank you, that did it. Note that I had to disable ghc-modi as well though.

Also I updated Atom, but that didn't change anything regarding the problem.

**Comment by lierdakil** [comment]
Also note: this seems to happen only with particular Stack versions or in exoctic configurations. Might also help to upgrade your stack installation.
