### ISSUE TITLE
ghc [--]version

### ISSUE THREAD

**Issue by johngeorgewright** [atom-haskell/haskell-ghc-mod#219]
Just trying out this package on my linux machine with a fresh install of ghc (via stack).

1. `stack setup`
1. Add direct path of ghc executable to settings `~/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc`

It seems, to get the version of this ghc, the syntax uses the hyphenated option:

```
$> ~/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
```

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 1.19.9

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. 1

```
At Error: Command failed: /home/john/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc version
target ‘version’ is not a module name or a source file

PATH: /home/john/.nvm/versions/node/v8.4.0/bin:/home/john/.rvm/gems/ruby-2.2.1/bin:/home/john/.rvm/gems/ruby-2.2.1@global/bin:/home/john/.rvm/rubies/ruby-2.2.1/bin:./node_modules/.bin:/home/john/.local/bin:/home/john/Workspace/pebble/PebbleSDK-3.6.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-9-oracle/bin:/usr/lib/jvm/java-9-oracle/db/bin:/home/john/.rvm/bin:/home/john/.rvm/bin:/snap/bin:/usr/lib/jvm/java-9-oracle/bin:/usr/lib/jvm/java-9-oracle/db/bin:/usr/local/heroku/bin:/home/john/.rvm/bin:/home/john/.rvm/bin:/home/john/.rvm/bin
path: undefined
Path: undefined

Error
    at /packages/haskell-ghc-mod/lib/util.coffee:60:26
    at ChildProcess.exithandler (child_process.js:225:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
  4x -9:48.9.0 vim-mode-plus:move-down (input.hidden-input)
     -9:47.5.0 vim-mode-plus:move-up (input.hidden-input)
  7x -9:47.2.0 vim-mode-plus:move-down (input.hidden-input)
  2x -9:41.6.0 vim-mode-plus:move-up (input.hidden-input)
     -9:40.4.0 intentions:highlight (input.hidden-input)
     -9:40.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
80s-pastel-syntax 1.2.0 
ariake-dark-syntax 0.1.3 
atom-beautify 0.30.5 
atom-ctags 5.1.0 
atom-jade 0.3.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-minify 0.8.0 
atom-sync 0.7.3 
atom-typescript 11.0.6 
atomic-chrome 0.3.2 
auto-indent 0.5.0 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
coffee-compile 0.26.0 
compare-files 0.8.1 
conceal 0.0.4 
copy-as-rtf 0.9.3 
devdocs 0.2.1 
docblockr 0.11.0 
editorconfig 2.2.2 
file-icons 2.1.11 
flatwhite-syntax 0.8.1 
flow-ide 1.8.1 
git-blame 1.2.1 
git-control 0.9.0 
git-plus 7.9.3 
git-time-machine 1.5.9 
grammar-token-limit 0.1.1 
haskell-ghc-mod 1.19.9 
highlight-column 0.5.4 
hyperclick 0.1.3 
ide-haskell 1.9.6 
intentions 1.1.5 
ionide-fsharp 1.9.3 
jumpy 3.1.3 
language-apache 1.7.0 
language-babel 2.71.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-dot-template 0.2.0 
language-erlang 3.2.0 
language-fsharp 0.8.4 
language-gherkin 1.0.4 
language-groovy 0.7.0 
language-haml 0.25.1 
language-haskell 1.13.1 
language-jade 0.7.2 
language-livescript 0.0.3 
language-postcss 1.3.1 
language-proto 0.8.0 
language-pug 0.0.21 
language-robot-framework 2.2.0 
language-rust 0.4.12 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-clojure 1.1.3 
linter-coffeelint 1.3.1 
linter-csslint 1.3.4 
linter-erb 1.1.0 
linter-erlang 0.4.0 
linter-eslint 8.2.1 
linter-flow 5.6.0 
linter-gcc 0.7.1 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-jsonlint 1.3.0 
linter-jsxhint 0.1.2 
linter-less 2.6.0 
linter-pug 1.3.1 
linter-pylint 2.1.0 
linter-rubocop 2.1.1 
linter-rust 0.8.0 
linter-scss-lint 3.1.0 
linter-shellcheck 1.4.4 
linter-stylelint 4.0.1 
linter-tslint 1.7.0 
linter-ui-default 1.6.7 
linter-write-good 0.9.0 
local-history 4.3.0 
merge-conflicts 1.4.5 
multi-cursor 2.1.5 
navigate 0.1.17 
nord-atom-syntax 0.9.1 
nrepl 0.4.0 
pastel-dark-theme 0.1.2 
pigments 0.39.1 
pinned-tabs 1.3.0 
project-manager 3.3.5 
quick-highlight 0.10.0 
sort-lines 0.14.0 
source-preview-pug 0.2.0 
spacegray-dark-ui 0.13.0 
spacegray-eighties-ui 2.0.0 
split-diff 1.4.4 
Stylus 3.1.1 
sync-settings 0.8.2 
toggle-quotes 1.0.1 
tomorrow 1.0.0 
tomorrow-night-eighties-syntax 1.0.2 
tree-view-search-bar 0.1.8 
vim-mode-clipboard-plus 0.2.0 
vim-mode-plus 0.96.2 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by johngeorgewright** [comment]
Many apologies. I'm a newb to this... ignorant assumption ghc/ghc-mod were the same thing.

1. `stack install ghc-mod`
1. Remove previous setting added for ghc-mod path

**Comment by lierdakil** [comment]
Glad to see you figured it out. I should probably mention, however, that you're using Atom 1.18. Consider updating. Newest versions of ide-haskell and friends actually require Atom 1.19, so you're missing out on *some* stuff.

FWIW, there's actually a dedicated documentation site with some initial setup instructions: https://atom-haskell.github.io/ -- it does beg for more complete tutorials though.
