### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch.It is probably missing or misconfigured. EACCES

### ISSUE THREAD

**Issue by vioqiao** [atom-haskell/haskell-ghc-mod#222]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.9.5
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.1.0

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured. EACCES

```
At Error was: Error
spawn EACCES
Debug information:
{
  "dir": "/Users/qiaozihan",
  "err": {
    "code": "EACCES",
    "errno": "EACCES",
    "syscall": "spawn"
  },
  "opts": {
    "cwd": "/Users/qiaozihan",
    "env": {
      "PATH": "/Users/qiaozihan/.stack/global-project/.stack-work/install/x86_64-osx/lts-9.5/8.0.2/bin:/Users/qiaozihan/.stack/snapshots/x86_64-osx/lts-9.5/8.0.2/bin:/Users/qiaozihan/.stack/programs/x86_64-osx/ghc-8.0.2/bin:/usr/local/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    },
    "encoding": "utf8",
    "maxBuffer": null
  }
}
Environment (filtered):
{
  "PATH": "/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
}


Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at Object.exports.execFile (child_process.js:160:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:200:20)
    at Promise (/packages/haskell-ghc-mod/lib/util.js:70:30)
    at /packages/haskell-ghc-mod/lib/util.js:68:16)
    at Generator.next (<anonymous>)
    at /packages/haskell-ghc-mod/lib/util.js:7:71
    at __awaiter (/packages/haskell-ghc-mod/lib/util.js:3:12)
    at Object.execPromise (/packages/haskell-ghc-mod/lib/util.js:67:12)
    at /packages/haskell-ghc-mod/lib/ghc-mod/index.js:358:43)
    at Generator.next (<anonymous>)
    at /packages/haskell-ghc-mod/lib/ghc-mod/index.js:7:71
    at __awaiter (/packages/haskell-ghc-mod/lib/ghc-mod/index.js:3:12)
    at GhcModiProcess.getVersion (/packages/haskell-ghc-mod/lib/ghc-mod/index.js:355:16)
    at /packages/haskell-ghc-mod/lib/ghc-mod/index.js:326:36)
    at Generator.next (<anonymous>)
    at fulfilled (/packages/haskell-ghc-mod/lib/ghc-mod/index.js:4:58)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.1.0 
ide-haskell 2.0.5 
ide-haskell-cabal 2.0.2 
ide-haskell-repl 0.7.1 
language-haskell 1.14.1 
script 3.16.0 
```

**Comment by lierdakil** [comment]
Probably a directory specified as 'ghc-mod path'. In most cases, you should leave 'ghc-mod path' as `ghc-mod` (the default). If using stack exclusively, you should probably leave 'additional path directories' alone as well and just remember to run `stack build ghc-mod` in your project when switching resolvers.

**Comment by vioqiao** [comment]
Thank you so much!
