### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. ENOENT

### ISSUE THREAD

**Issue by mhdsysy** [atom-haskell/haskell-ghc-mod#228]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.1.2

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured. ENOENT

```
At Error was: Error
spawn ghc-mod ENOENT
Debug information:
{
  "dir": "C:\\Users\\DELL\\Desktop",
  "err": {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn ghc-mod",
    "path": "ghc-mod",
    "spawnargs": [
      "version"
    ],
    "cmd": "ghc-mod version"
  },
  "opts": {
    "cwd": "C:\\Users\\DELL\\Desktop",
    "env": {
      "Path": "C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Users\\DELL\\AppData\\Roaming\\cabal\\bin;C:\\Users\\DELL\\AppData\\Roaming\\local\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Users\\DELL\\AppData\\Local\\atom\\bin",
      "STACK_ROOT": "C:\\sr",
      "PATH": "C:\\sr\\global-project\\.stack-work\\install\\34070b1b\\bin;C:\\sr\\snapshots\\7eb65607\\bin;.;C:\\Users\\DELL\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\mingw\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\usr\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\usr\\local\\bin;C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Users\\DELL\\AppData\\Roaming\\cabal\\bin;C:\\Users\\DELL\\AppData\\Roaming\\local\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Users\\DELL\\AppData\\Local\\atom\\bin"
    },
    "encoding": "utf8",
    "maxBuffer": null
  }
}
Config:
{
  "onChangeCheck": true,
  "onChangeLint": true,
  "ghcModPath": "ghc-mod",
  "enableGhcModi": true,
  "lowMemorySystem": false,
  "debug": false,
  "additionalPathDirectories": [],
  "cabalSandbox": true,
  "stackSandbox": true,
  "initTimeout": 60,
  "interactiveInactivityTimeout": 60,
  "interactiveActionTimeout": 300,
  "onSaveCheck": true,
  "onSaveLint": true,
  "alwaysInteractiveCheck": true,
  "onMouseHoverShow": "typeAndInfo",
  "onSelectionShow": "",
  "maxBrowseProcesses": 2,
  "highlightTooltips": true,
  "highlightMessages": true,
  "hlintOptions": [],
  "experimental": false,
  "suppressGhcPackagePathWarning": false,
  "ghcModMessages": "console"
}
Environment (filtered):
{
  "Path": "C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Users\\DELL\\AppData\\Roaming\\cabal\\bin;C:\\Users\\DELL\\AppData\\Roaming\\local\\bin;C:\\Users\\DELL\\AppData\\Local\\Programs\\MiKTeX 2.9\\miktex\\bin\\x64\\;C:\\Users\\DELL\\AppData\\Local\\atom\\bin",
  "STACK_ROOT": "C:\\sr"
}


Error
    at CP.execFile (/packages/haskell-ghc-mod/lib/util.js:79:36)
    at exithandler (child_process.js:230:5)
    at ChildProcess.errorhandler (child_process.js:242:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-debug 0.3.4 
haskell-ghc-mod 2.1.2 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
haskell-pointfree 0.2.0 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.4 
ide-haskell-hasktags 0.0.12 
ide-haskell-repl 0.7.4 
language-haskell 1.14.3 
language-haskell-scoped 0.1.0 
```

**Comment by lierdakil** [comment]
It doesn't seem like you have a stack project set-up.

I'm guessing that you probably didn't install binary dependencies correctly. Please see here:
https://atom-haskell.github.io/installation/installing-binary-dependencies/

Also *please* pay close attention to warnings, those are there for a reason.

**Comment by lierdakil** [comment]
Closing due to inactivity.
