### ISSUE TITLE
Atom is not working

### ISSUE THREAD

**Issue by meizhangyadehuli** [atom-haskell/haskell-ghc-mod#229]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.1.1

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured. ENOENT

```
At Error was: Error
spawn C:\Users\Becca Dong\AppData\Local\Programs\stack\x86_64-windows ENOENT
Debug information:
{
  "dir": "F:\\I-FP",
  "err": {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows",
    "path": "C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows",
    "spawnargs": [
      "version"
    ],
    "cmd": "C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows version"
  },
  "opts": {
    "cwd": "F:\\I-FP",
    "env": {
      "Path": "C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;E:\\8.2.1\\lib\\extralibs\\bin;E:\\8.2.1\\bin;E:\\8.2.1 Haskell Platform\\lib\\extralibs\\bin;E:\\8.2.1 Haskell Platform\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;E:\\8.2.1 Haskell Platform\\mingw\\bin;E:\\8.2.1\\mingw\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\mingw\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\Becca Dong\\AppData\\Roaming\\cabal\\bin;C:\\Users\\Becca Dong\\AppData\\Roaming\\local\\bin;E:\\8.2.1\\bin;E:\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Becca Dong\\AppData\\Local\\atom\\bin",
      "STACK_ROOT": "C:\\sr",
      "PATH": "C:\\sr\\global-project\\.stack-work\\install\\7abedeba\\bin;C:\\sr\\snapshots\\fe0c6596\\bin;.;C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\mingw\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\mingw64\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\usr\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows\\msys2-20150512\\usr\\local\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\bin\\ghc;C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;E:\\8.2.1\\lib\\extralibs\\bin;E:\\8.2.1\\bin;E:\\8.2.1 Haskell Platform\\lib\\extralibs\\bin;E:\\8.2.1 Haskell Platform\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;E:\\8.2.1 Haskell Platform\\mingw\\bin;E:\\8.2.1\\mingw\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\mingw\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\Becca Dong\\AppData\\Roaming\\cabal\\bin;C:\\Users\\Becca Dong\\AppData\\Roaming\\local\\bin;E:\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Becca Dong\\AppData\\Local\\atom\\bin"
    },
    "encoding": "utf8",
    "maxBuffer": null
  }
}
Config:
{
  "additionalPathDirectories": [
    "C:\\Program Files\\Haskell Platform\\8.0.2-a\\bin\\ghc"
  ],
  "ghcModPath": "C:\\Users\\Becca Dong\\AppData\\Local\\Programs\\stack\\x86_64-windows",
  "enableGhcModi": true,
  "lowMemorySystem": false,
  "debug": false,
  "cabalSandbox": true,
  "stackSandbox": true,
  "initTimeout": 60,
  "interactiveInactivityTimeout": 60,
  "interactiveActionTimeout": 300,
  "onSaveCheck": true,
  "onSaveLint": true,
  "onChangeCheck": false,
  "onChangeLint": false,
  "alwaysInteractiveCheck": true,
  "onMouseHoverShow": "typeAndInfo",
  "onSelectionShow": "",
  "maxBrowseProcesses": 2,
  "highlightTooltips": true,
  "highlightMessages": true,
  "hlintOptions": [],
  "experimental": false,
  "suppressGhcPackagePathWarning": false,
  "ghcModMessages": "console"
}
Environment (filtered):
{
  "Path": "C:\\Program Files\\Haskell\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\lib\\extralibs\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\bin;E:\\8.2.1\\lib\\extralibs\\bin;E:\\8.2.1\\bin;E:\\8.2.1 Haskell Platform\\lib\\extralibs\\bin;E:\\8.2.1 Haskell Platform\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;E:\\8.2.1 Haskell Platform\\mingw\\bin;E:\\8.2.1\\mingw\\bin;C:\\Program Files\\Haskell Platform\\8.2.1\\mingw\\bin;C:\\Program Files\\OpenVPN\\bin;C:\\Program Files\\Haskell Platform\\8.0.2-a\\mingw\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\Becca Dong\\AppData\\Roaming\\cabal\\bin;C:\\Users\\Becca Dong\\AppData\\Roaming\\local\\bin;E:\\8.2.1\\bin;E:\\bin;C:\\Users\\Becca Dong\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Becca Dong\\AppData\\Local\\atom\\bin",
  "STACK_ROOT": "C:\\sr"
}


Error
    at CP.execFile (/packages/haskell-ghc-mod/lib/util.js:79:36)
    at exithandler (child_process.js:230:5)
    at ChildProcess.errorhandler (child_process.js:242:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.1.1 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.3 
ide-haskell-repl 0.7.3 
language-haskell 1.14.3 
```

**Comment by lierdakil** [comment]
You've set `ghcModPath` to a directory. And apparently nonexistent directory at that. It should point to ghc-mod *executable*. FWIW, leaving it as default `ghc-mod`, and only manipulating `additionalPathDirectories` is the preferred way of dealing with search paths.

You also seem to be using stack, that has some caveats of it's own. In any case, please review https://atom-haskell.github.io/core-packages/haskell-ghc-mod/ , especially 'Configuration' and 'Using with stack' sections.
