### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. 

### ISSUE THREAD

**Issue by moesysy** [atom-haskell/haskell-ghc-mod#233]
GHCi, version 7.10.3
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.1.3

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured. ENOENT

```
At Error was: Error
spawn ghc-mod ENOENT
Debug information:
{
  "dir": "/home/moe/Downloads",
  "err": {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn ghc-mod",
    "path": "ghc-mod",
    "spawnargs": [
      "version"
    ],
    "cmd": "ghc-mod version"
  },
  "opts": {
    "cwd": "/home/moe/Downloads",
    "env": {
      "PATH": "/home/user/ghc-mod-sandbox/bin:/home/moe/bin:/home/moe/.local/bin:/home/moe/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    },
    "encoding": "utf8",
    "maxBuffer": null
  }
}
Config:
{
  "additionalPathDirectories": [
    "/home/user/ghc-mod-sandbox/bin"
  ],
  "ghcModPath": "ghc-mod",
  "enableGhcModi": true,
  "lowMemorySystem": false,
  "debug": false,
  "cabalSandbox": true,
  "stackSandbox": true,
  "initTimeout": 60,
  "interactiveInactivityTimeout": 60,
  "interactiveActionTimeout": 300,
  "onSaveCheck": true,
  "onSaveLint": true,
  "onChangeCheck": false,
  "onChangeLint": false,
  "alwaysInteractiveCheck": true,
  "onMouseHoverShow": "typeAndInfo",
  "onSelectionShow": "",
  "maxBrowseProcesses": 2,
  "highlightTooltips": true,
  "highlightMessages": true,
  "hlintOptions": [],
  "experimental": false,
  "suppressGhcPackagePathWarning": false,
  "ghcModMessages": "console",
  "maxMemMegs": 4096
}
Environment (filtered):
{
  "PATH": "/home/moe/bin:/home/moe/.local/bin:/home/moe/.cabal/bin:/opt/cabal/1.22/bin:/opt/ghc/7.10.3/bin:/home/moe/bin:/home/moe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
}


Error
    at CP.execFile (/packages/haskell-ghc-mod/lib/util.js:79:36)
    at exithandler (child_process.js:230:5)
    at ChildProcess.errorhandler (child_process.js:242:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.1.3 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.4 
language-haskell 1.14.3 
```

**Comment by lierdakil** [comment]
Atom can't find ghc-mod.

Double-check if `/home/user/ghc-mod-sandbox/bin/ghc-mod` exists. Optionally run `find /home/user/ghc-mod-sandbox -iname ghc-mod`.
