### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. ENOENT

### ISSUE THREAD

**Issue by AlexandruBuhai** [atom-haskell/haskell-ghc-mod#234]
1. Start atom with a .hs file

I installed ghc-mod by using the atom interface.
Cabal version: cabal-install version 1.24.0.2
compiled using version 1.24.2.0 of the Cabal library 

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.1.3

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured. ENOENT

```
At Error was: Error
spawn ghc-mod ENOENT
Debug information:
{
  "dir": "/home/abuhai/functional_programming",
  "err": {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn ghc-mod",
    "path": "ghc-mod",
    "spawnargs": [
      "version"
    ],
    "cmd": "ghc-mod version"
  },
  "opts": {
    "cwd": "/home/abuhai/functional_programming",
    "env": {
      "PATH": "/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/abuhai/.local/bin:/home/abuhai/bin"
    },
    "encoding": "utf8",
    "maxBuffer": null
  }
}
Config:
{
  "lowMemorySystem": true,
  "onChangeCheck": true,
  "onChangeLint": true,
  "ghcModPath": "ghc-mod",
  "enableGhcModi": true,
  "debug": false,
  "additionalPathDirectories": [],
  "cabalSandbox": true,
  "stackSandbox": true,
  "initTimeout": 60,
  "interactiveInactivityTimeout": 60,
  "interactiveActionTimeout": 300,
  "onSaveCheck": true,
  "onSaveLint": true,
  "alwaysInteractiveCheck": true,
  "onMouseHoverShow": "typeAndInfo",
  "onSelectionShow": "",
  "maxBrowseProcesses": 2,
  "highlightTooltips": true,
  "highlightMessages": true,
  "hlintOptions": [],
  "experimental": false,
  "suppressGhcPackagePathWarning": false,
  "ghcModMessages": "console",
  "maxMemMegs": 4096
}
Environment (filtered):
{
  "PATH": "/usr/lib64/qt-3.3/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/abuhai/.local/bin:/home/abuhai/bin"
}


Error
    at CP.execFile (/packages/haskell-ghc-mod/lib/util.js:79:36)
    at exithandler (child_process.js:230:5)
    at ChildProcess.errorhandler (child_process.js:242:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:20.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-beautify 0.30.9 
atom-haskell 0.4.0 
atom-material-syntax 1.0.7 
atom-material-ui 2.0.6 
atom-monokai 0.10.9 
autocomplete-haskell 1.0.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
darkula-syntax 0.3.0 
file-icons 2.1.14 
git-plus 7.10.0 
git-time-machine 1.5.9 
goto-definition 1.3.4 
haskell-ghc-mod 2.1.3 
haskell-pointfree 0.2.0 
haskell-scry 1.0.7 
hasklig 0.4.0 
highlight-selected 0.13.1 
hyperclick 0.1.5 
hyperlink-hyperclick 1.3.4 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.5 
ide-haskell-hasktags 0.0.12 
ide-haskell-hoogle 0.1.2 
ide-haskell-repl 0.7.6 
intentions 1.1.5 
language-haskell 1.14.3 
language-haskell-scoped 0.1.0 
linter 2.2.0 
linter-flake8 2.2.1 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-py 1.1.0 
linter-pylint 2.1.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
one-dark-vivid-syntax 1.8.0 
open-recent 5.0.0 
operator-mono 0.11.0 
pane-layout-plus 0.7.4 
pigments 0.40.2 
python-indent 1.1.4 
seti-ui 1.9.0 
todo-show 2.1.0 
wordcount 2.10.4 
```

**Comment by lierdakil** [comment]
Please see https://atom-haskell.github.io/installation/installing-binary-dependencies/
