### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Sym...

### ISSUE THREAD

**Issue by Qunkero** [atom-haskell/haskell-ghc-mod#239]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package 2.2.3

### Stack Trace

Uncaught TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Symbol() { [native code] }'

```
At C:\Users\Qunkero\.atom\packages\haskell-ghc-mod\lib\ghc-mod\interactive-process.js:10

TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Symbol() { [native code] }'
    at /packages/haskell-ghc-mod/lib/ghc-mod/interactive-process.js:10:22)
    at /packages/haskell-ghc-mod/lib/ghc-mod/interactive-process.js:186:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.js:4:31)
    at /packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.js:187:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real-factory.js:4:33)
    at /packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real-factory.js:201:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.28.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/haskell-ghc-mod/lib/ghc-mod/index.js:8:41)
    at /packages/haskell-ghc-mod/lib/ghc-mod/index.js:460:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.28.0/resources/app/src/native-compile-cache.js:106:36)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
git-plus 7.12.0 
haskell-ghc-mod 2.2.3 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
language-haskell 1.17.8 
platformio-ide-terminal 2.8.3 
```

**Comment by lierdakil** [comment]
Hello. Thanks for your report! Should be fixed in v2.2.4 -- please let me know if not.
