### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUri' of null

### ISSUE THREAD

**Issue by edwardIshaq** [atom-haskell/haskell-ghc-mod#36]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.8.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getUri' of null

```
At /Users/edward/.atom/packages/haskell-ghc-mod/lib/util.coffee:14

TypeError: Cannot read property 'getUri' of null
  at /Users/edward/.atom/packages/haskell-ghc-mod/lib/util.coffee:14:26
  at Array.filter (native)
  at Object.module.exports.Util.getRootDir (/Users/edward/.atom/packages/haskell-ghc-mod/lib/util.coffee:13:43)
  at CompletionBackend.module.exports.CompletionBackend.getModuleMap (/Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:61:21)
  at CompletionBackend.getModuleMap (/Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:1:1)
  at CompletionBackend.module.exports.CompletionBackend.getSymbolsForBuffer (/Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:35:29)
  at CompletionBackend.getSymbolsForBuffer (/Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:1:1)
  at CompletionBackend.module.exports.CompletionBackend.getCompletionsForSymbol (/Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:177:6)
  at /Users/edward/.atom/packages/haskell-ghc-mod/lib/completion-backend.coffee:1:1
  at SuggestionBuilder.module.exports.SuggestionBuilder.processSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:51:5)
  at SuggestionBuilder.processSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:1:1)
  at SuggestionBuilder.module.exports.SuggestionBuilder.symbolSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:55:6)
  at SuggestionBuilder.symbolSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:1:1)
  at SuggestionBuilder.module.exports.SuggestionBuilder.getSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:94:10)
  at SuggestionBuilder.getSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/suggestion-builder.coffee:1:1)
  at Object.getSuggestions (/Users/edward/.atom/packages/autocomplete-haskell/lib/autocomplete-haskell.coffee:43:49)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:221:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -2:29.9.0 core:copy (atom-text-editor.editor.is-focused)
  2x -2:28.1.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -2:23.1.0 core:paste (atom-text-editor.editor.is-focused)
     -2:22.1.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -2:21.1.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
 12x -2:20.6.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -2:18.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:18.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:17.8.0 core:delete (atom-text-editor.editor.is-focused)
     -2:17.5.0 core:save (atom-text-editor.editor.is-focused)
     -2:17.5.0 ide-haskell:check-file (atom-text-editor.editor.is-focused)
     -2:17.5.0 ide-haskell:lint-file (atom-text-editor.editor.is-focused)
     -0:19.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:13.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.4
ide-haskell, v0.6.2
language-haskell, v1.2.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
v0.8.5 could probably fix this. If you're able to reproduce, please try and report back. Thanks.
