### ISSUE TITLE
Uncaught Error: Error: Command failed: ghc-mod type /var/folders/28/hhwsccr90x7_bwdl4dyl292m0000gn/T/haskell-ghc-mod11529-2337-ugp709.hs  31 3/Users/LiuMS/GitHub/BBQ/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by notcome** [atom-haskell/haskell-ghc-mod#4]
I am trying to use haskell-ghc-mod but haven't made any progress. Initially, whenever I tried to check an identifier's type, an error of "This socket is closed." was thrown. Later, I disabled "Enable Ghc Modi", the following problem appeared. Besides, whenever I save a file, the same error is thrown. (Considering the "check on save" I think this is reasonable).

I haven't used ghc-mod with any other ide/editors yet. It was installed through cabal and is indeed the latest version.

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.3
**Thrown From**: [haskell-ghc-mod](https://github.com/lierdakil/haskell-ghc-mod) package, v0.4.3

### Stack Trace

Uncaught Error: Error: Command failed: ghc-mod type /var/folders/28/hhwsccr90x7_bwdl4dyl292m0000gn/T/haskell-ghc-mod11529-2337-ugp709.hs  31 3
/Users/LiuMS/GitHub/BBQ/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

```
At /Users/LiuMS/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70

Error: Error: Command failed: ghc-mod type /var/folders/28/hhwsccr90x7_bwdl4dyl292m0000gn/T/haskell-ghc-mod11529-2337-ugp709.hs  31 3
/Users/LiuMS/GitHub/BBQ/dist/setup-config: hGetContents: invalid argument (invalid byte sequence)

  at /Users/LiuMS/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:70:17
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:147:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -3:13.7 editor:newline (atom-text-editor.editor.is-focused)
  3x -3:10.7 autocomplete-plus:select-next (atom-text-editor.editor.is-focused)
     -3:08.7 editor:newline (atom-text-editor.editor.is-focused)
  5x -3:07.8 core:backspace (atom-text-editor.editor.is-focused)
     -2:48.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "enableGhcModi": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.2.0
haskell-ghc-mod, v0.4.3
ide-haskell, v0.3.5
language-haskell, v1.0.0

# Dev
No dev packages
```

**Comment by notcome** [comment]
It seems to be an inconsistence of versions between my cabal and ghc.

**Comment by lierdakil** [comment]
Please see https://github.com/kazu-yamamoto/ghc-mod/wiki/InconsistentCabalVersions
