### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Valdsonjr** [atom-haskell/haskell-ghc-mod#41]
1. Got this when trying to write anything

**Atom Version**: 1.0.5
**System**: Microsoft Windows 10 Pro
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.8.8

### Stack Trace

Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```
At C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\pathwatcher\lib\directory.js:49

TypeError: Cannot read property 'toLowerCase' of undefined
  at new Directory (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\pathwatcher\lib\directory.js:49:39)
  at Object.module.exports.Util.getRootDir (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\util.coffee:19:41)
  at CompletionBackend.module.exports.CompletionBackend.getModuleMap (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:63:21)
  at CompletionBackend.getModuleMap (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:1:1)
  at CompletionBackend.module.exports.CompletionBackend.getSymbolsForBuffer (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:35:29)
  at CompletionBackend.getSymbolsForBuffer (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:1:1)
  at CompletionBackend.module.exports.CompletionBackend.getCompletionsForSymbol (C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:179:6)
  at C:\Users\by_va\.atom\packages\haskell-ghc-mod\lib\completion-backend.coffee:1:1
  at SuggestionBuilder.module.exports.SuggestionBuilder.processSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:51:5)
  at SuggestionBuilder.processSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:1:1)
  at SuggestionBuilder.module.exports.SuggestionBuilder.symbolSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:55:6)
  at SuggestionBuilder.symbolSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:1:1)
  at SuggestionBuilder.module.exports.SuggestionBuilder.getSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:94:10)
  at SuggestionBuilder.getSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\suggestion-builder.coffee:1:1)
  at Object.getSuggestions (C:\Users\by_va\.atom\packages\autocomplete-haskell\lib\autocomplete-haskell.coffee:43:49)
  at C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:233:19)
  at AutocompleteManager.findSuggestions (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at atom-text-editor.subscriptions.add.atom.commands.add.autocomplete-plus:activate (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:209:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\by_va\AppData\Local\atom\app-1.0.5\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -1:48.7.0 grammar-selector:show (atom-text-editor.editor)
  4x -1:45.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai-plus"
    ]
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.8
ide-haskell, v0.7.1
language-haskell, v1.3.1
language-lua, v0.9.4
monokai-plus, v0.1.2

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Try v0.8.9, hopefully it works out. That said, I strongly suggest you open Atom on project directory, e.g. `atom path/to/your/project` (or 'Add Project Folder' from 'File' menu)

**Comment by Valdsonjr** [comment]
Everything seems fine, thanks!
