### ISSUE TITLE
Failed to load the haskell-ghc-mod package

### ISSUE THREAD

**Issue by ghost** [atom-haskell/haskell-ghc-mod#47]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v0.8.14

### Stack Trace

Failed to load the haskell-ghc-mod package

```
At Cannot find module 'temp'

Error: Cannot find module 'temp'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\util.coffee:3:8)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\util.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\ghc-modi-process.coffee:2:8)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\ghc-modi-process.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\haskell-ghc-mod.coffee:1:18)
    at Object.<anonymous> (C:\Users\HP I3\.atom\packages\haskell-ghc-mod-0.8.14\lib\haskell-ghc-mod.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package.js:759:34)
    at C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package.js:190:28
    at Package.module.exports.Package.measure (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package.js:167:15)
    at Package.module.exports.Package.load (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package.js:181:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package-manager.js:405:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\package-manager.js:369:14)
    at Atom.module.exports.Atom.startEditorWindow (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\atom.js:667:21)
    at Object.<anonymous> (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:12:8)
    at Object.<anonymous> (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\window-bootstrap.js:23:4)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .js] (C:\Users\HP I3\AppData\Local\atom\app-1.0.9\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at setupWindow (file:///C:/Users/HP%20I3/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:82:25)
    at window.onload (file:///C:/Users/HP%20I3/AppData/Local/atom/app-1.0.9/resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\GitHub"
  }
}
```

### Installed Packages

```coffee
# User
ide-haskell, v0.7.1
language-haskell, v1.4.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Please try reinstalling. Apparently, there was a problem with installation.
29 авг. 2015 г. 9:17 пользователь "Chandra A." <notifications@github.com>
написал:

**Comment by lierdakil** [comment]
Closing due to lack of activity
