### ISSUE TITLE
Failed to load the haskell-ghc-mod package

### ISSUE THREAD

**Issue by achernyak** [atom-haskell/haskell-ghc-mod#77]
This error started happening on start up with the latest version. Until today, everything was working perfectly.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.2.7

### Stack Trace

Failed to load the haskell-ghc-mod package

```
At Cannot find module 'temp'

Error: Cannot find module 'temp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/util.coffee:3:8)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/util.coffee:1:1)
    at Module._compile (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:2:8)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:1:1)
    at Module._compile (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:1:18)
    at Object.<anonymous> (file:///C:/Users/blank/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:1:1)
    at Module._compile (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\blank\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:663:34)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.2.7
haskell-pointfree, v0.1.2
ide-haskell, v1.3.8
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.11
language-haskell, v1.5.1
minimap, v4.19.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Update issue. Please uninstall then reinstall.

**Comment by achernyak** [comment]
That worked. Thanks for the quick reply.
