### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch.It is probably missing or misconfigured.

### ISSUE THREAD

**Issue by TheDemx27** [atom-haskell/haskell-ghc-mod#78]
[Enter steps to reproduce below:]

Just installed the required  atom packages and haskell. I have the cabal bin folder in my path.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Home
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.3.0

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured.

Restart Atom after configuring.

```
At Error: spawnSync ghc-mod ENOENT

Error: spawnSync ghc-mod ENOENT
    at exports._errnoException (util.js:837:11)
    at Object.spawnSync (child_process.js:432:20)
    at new GhcModiProcess (file:///C:/Users/Chris/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:24:14)
    at Object.module.exports.HaskellGhcMod.activate (file:///C:/Users/Chris/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:84:18)
    at Package.module.exports.Package.activateNow (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:170:19)
    at C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:150:32
    at Package.module.exports.Package.measure (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:92:15)
    at C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:143:26
    at Package.module.exports.Package.activate (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:517:21)
    at C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\atom-environment.js:686:21)
    at module.exports (C:\Users\Chris\AppData\Local\atom\app-1.3.2\resources\app.asar\src\initialize-application-window.js:28:10)
    at setupWindow (file:///C:/Users/Chris/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///C:/Users/Chris/AppData/Local/atom/app-1.3.2/resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "haskell-ghc-mod": {}
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-material-ui, v0.8.0
haskell-ghc-mod, v1.3.0
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
You probably need to install ghc-mod. `cabal install ghc-mod` or something, maybe?

If you have it installed, try to specify full path to ghc-mod executable in haskell-ghc-mod settings.

**Comment by TheDemx27** [comment]
Yep, I didn't have ghc-mod installed. Thanks!
