### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch.It is probably missing or misconfigured.

### ISSUE THREAD

**Issue by askl56** [atom-haskell/haskell-ghc-mod#79]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.3.0

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch.
It is probably missing or misconfigured.

Restart Atom after configuring.

```
At Error: spawnSync ghc-mod ENOENT

Error: spawnSync ghc-mod ENOENT
    at exports._errnoException (util.js:837:11)
    at Object.spawnSync (child_process.js:432:20)
    at new GhcModiProcess (/Users/andrew/.atom/packages/haskell-ghc-mod/lib/ghc-modi-process.coffee:24:14)
    at Object.module.exports.HaskellGhcMod.activate (/Users/andrew/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:84:18)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:517:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:499:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:494:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:478:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:686:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.25.0
haskell-ghc-mod, v1.3.0
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.1

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
1. Do you have Haskell Platform or similar?
2. Do you have ghc-mod installed?
3. Is it on your PATH?

If answer to all of the above questions is 'yes', you likely need to set 'Additional Path Directories' in haskell-ghc-mod settings to reflect your PATH. OSX has some weirdness w.r.t. PATH inheritance.

If answer to last question is 'no', you need to specify full path to ghc-mod executable in 'ghc-mod Path' *in addition* to above.

**Comment by lierdakil** [comment]
Closing due to inactivity
