### ISSUE TITLE
ghc-modi said: ghc-mod: unknown command: `import'

### ISSUE THREAD

**Issue by tebello-thejane** [atom-haskell/haskell-ghc-mod#82]
Hey, peeps. Sorry in advance for the wall of text:

```
caps: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
URI: /home/zyxoas/work/slang/src/DataSource/Fenix.hs
Args: ,Data.ByteString
message: 
log:

...

-0.045s: ghc-modi said: ghc-mod: unknown command: `import'
0s: ghc-modi for /home/zyxoas/work/slang ended with 1
0s: ghc-modi for /home/zyxoas/work/slang ended with 1
0s: Running ghc-modi command unmap-file,/home/zyxoas/work/slang/src/DataSource/Fenix.hs
0s: ghc-modi crashed
```

This happens when I hover my mouse over the word `import` in the source file.

I apologise for cutting so much out of the log. Some of this is sensitive.

```
ghc-modi crashed
    at module.exports.Util.mkError (/home/zyxoas/.atom/packages/haskell-ghc-mod/lib/util.coffee:123:15)
    at ChildProcess.exitCallback (/home/zyxoas/.atom/packages/haskell-ghc-mod/lib/interactive-process.coffee:76:20)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by lierdakil** [comment]
Please post full log here. Preferably just use Atom's 'report error'
button.
4 янв. 2016 г. 14:34 пользователь "Tebello Thejane" <
notifications@github.com> написал:

**Comment by lierdakil** [comment]
Closing due to no activity. Provided log is insufficient for anything really.
