### ISSUE TITLE
Haskell-ghc-mod: ghc-mod command check failed with error code 1

### ISSUE THREAD

**Issue by clojj** [atom-haskell/haskell-ghc-mod#84]
This error also happened with many other cabal-projects (all have some lengthy cabal-file)

reproduce...
1. Open this repo (open folder) https://github.com/haskell-suite/haskell-names
2. Having the original cabal-file, produces this error (https://github.com/haskell-suite/haskell-names/blob/master/haskell-names.cabal)

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.4

### Stack Trace

Haskell-ghc-mod: ghc-mod command check failed with error code 1

```
At caps: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
URI: /Users/jwin/HaskellProjects/haskell-names/examples/HeadUsages.hs
Args: 
message: ghc-mod: cabal: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

log:
-0.043s: getProcessOptions(/Users/jwin/HaskellProjects/haskell-names)
-0.042s: PATH = /Users/jwin/Library/Haskell/bin:/usr/bin:/bin:/usr/sbin:/sbin
-0.042s: running /Users/jwin/Library/Haskell/bin/ghc-mod check,/Users/jwin/HaskellProjects/haskell-names/examples/HeadUsages.hs with options.cwd = /Users/jwin/HaskellProjects/haskell-names,options.env = [object Object],options.encoding = utf-8
-0.003s: ghc-mod said: ghc-mod: cabal: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
0s: /Users/jwin/Library/Haskell/bin/ghc-mod ended with code 1
0s: code 1: ghc-mod: cabal: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)


code 1: ghc-mod: cabal: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

    at module.exports.Util.mkError (/Users/jwin/.atom/packages/haskell-ghc-mod/lib/util.coffee:97:15)
    at BufferedProcess.exit (/Users/jwin/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.coffee:117:20)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -2:13.6.0 core:paste (atom-text-editor#haskell-ghc-mod.additionalPathDirectories.editor.mini.is-focused)
     -2:01.7.0 haskell-ghc-mod:check-file (atom-text-editor.editor.is-focused)
  2x -2:00.6.0 ide-haskell:close-tooltip (atom-text-editor.editor.is-focused)
     -2:00.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:00.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:15.8.0 haskell-ghc-mod:check-file (atom-text-editor.editor.is-focused)
  2x -1:14.4.0 ide-haskell:close-tooltip (atom-text-editor.editor.is-focused)
     -1:14.4.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:14.4.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:31.7.0 haskell-ghc-mod:check-file (atom-text-editor.editor.is-focused)
  2x -0:30.6.0 ide-haskell:close-tooltip (atom-text-editor.editor.is-focused)
     -0:30.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:30.6.0 core:cancel (atom-text-editor.editor.is-focused)
  4x -0:24.6.0 core:backspace (atom-text-editor#ide-haskell-cabal.pathTo710.editor.mini.is-focused)
     -0:21.6.0 core:save (atom-text-editor#ide-haskell-cabal.pathTo710.editor.mini.is-focused)
     -0:01.4.0 haskell-ghc-mod:check-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "spell-check",
      "cursor-history",
      "cabal",
      "wrap-guide",
      "metrics",
      "highlight-selected",
      "hover-tooltips-hdevtools"
    ],
    "packagesWithKeymapsDisabled": [
      "ide-haskell",
      "term3",
      "cursor-history"
    ],
    "themes": [
      "one-dark-ui",
      "necro-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "/Users/jwin/Library/Haskell/bin/ghc-mod",
    "ghcModiPath": "/Users/jwin/Library/Haskell/bin/ghc-modi",
    "debug": false,
    "additionalPathDirectories": [
      "/Users/jwin/Library/Haskell/bin"
    ]
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
atom-wallaby, v1.0.7
autocomplete-haskell, v0.6.2
compare-files, v0.6.2
file-icons, v1.6.13
haskell-ghc-mod, v1.5.4
haskell-pointfree, v0.1.3
highlight-column, v0.5.0
hindent, v0.0.1
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
ide-haskell-repl, v0.0.17
language-haskell, v1.5.2
necro-syntax, v1.0.0
project-manager, v2.7.1
quick-highlight, v0.3.10
term3, v0.21.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Apparently, ghc-mod can't find 'cabal' executable. Probably you'll have to
adjust additional path directories setting.
8 янв. 2016 г. 1:34 пользователь "clojj" <notifications@github.com> написал:

**Comment by lierdakil** [comment]
Closing due to age
