### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. EACCES

### ISSUE THREAD

**Issue by NZQiu** [atom-haskell/haskell-ghc-mod#85]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.4

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. EACCES

```
At Error: spawn EACCES
PATH: /Users/GQiu/.rvm/gems/ruby-head/bin:/Users/GQiu/.rvm/gems/ruby-head@global/bin:/Users/GQiu/.rvm/rubies/ruby-head/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/GQiu/.rvm/bin:/Users/GQiu/Library/Haskell/bin
path: undefined
Path: undefined

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at Object.exports.execFile (child_process.js:153:15)
    at Object.module.(anonymous function) [as execFile] (ATOM_SHELL_ASAR.js:163:20)
    at /Users/GQiu/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:56:10
    at GhcModiProcess.module.exports.GhcModiProcess.getVersion (/Users/GQiu/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:55:9)
    at new GhcModiProcess (/Users/GQiu/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:24:8)
    at Object.module.exports.HaskellGhcMod.activate (/Users/GQiu/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:79:16)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:786:28
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:533:41)
    at Immediate._onImmediate (/Users/GQiu/.atom/packages/language-haskell/src/main.coffee:7:23)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "haskell-ghc-mod": {
    "ghcModPath": "/Users/GQiu/Library/Haskell/bin",
    "additionalPathDirectories": [
      "/Users/GQiu/Library/Haskell/bin"
    ],
    "ghcModiPath": "/Users/GQiu/Library/Haskell/bin",
    "enableGhcModi": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.5.4
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.2
linter-hlint, v0.4.2
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
`ghcModPath` should probably be `/Users/GQiu/Library/Haskell/bin/ghc-mod`. README explicitly states that it should be path to *executable*, not a directory that contains said executable.

**Comment by NZQiu** [comment]
Yeah, Thanks indeed.
