### ISSUE TITLE
ghc 7.10.3: message: Not a number ""

### ISSUE THREAD

**Issue by Heather** [atom-haskell/haskell-ghc-mod#88]
ghc-mod version 5.5.0.0 compiled by GHC 7.10.3

**Atom Version**: 1.3.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.5

### Stack Trace

Haskell-ghc-mod: ghc-mod interactive command type failed with error code 1

```
At caps: {"version":[5,5,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":false,"quoteArgs":true}
URI: F:\P\thridparty\M\Sharingan\src\Yaml.hs
Args: ,37,35
message: Not a number ""

Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

log:
-28.386s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-28.383s: PATH = .....AppData\Local\atom\bin
-28.383s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-28.382s: Failed. Falling back to ghc-mod
-28.382s: running ghc-mod info,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,RepositoryWrapper with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-28.322s: ghc-mod said: Warning: Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead.
-27.792s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-27.791s: PATH = .....AppData\Local\atom\bin
-27.42s: ghc-mod said: Warning: Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead.
-27.01s: ghc-mod said: EXCEPTION: info:
-27.01s: ghc-mod said:                parse error (possibly incorrect indentation or mismatched brackets)
-26.997s: ghc-mod ended with code 0
-26.997s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-26.997s: Failed. Falling back to ghc-mod
-26.997s: running ghc-mod type,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,32,34 with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-26.995s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-26.995s: PATH = .....AppData\Local\atom\bin
-26.978s: ghc-mod said: Not a number ""
-26.978s: ghc-mod said: 
-26.978s: ghc-mod said: Usage: ghc-mod type FILE LINE COL
-26.978s: ghc-mod said:   Get the type of the expression under (LINE,COL)
-26.976s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-26.976s: PATH = .....AppData\Local\atom\bin
-26.976s: ghc-mod ended with code 1
-26.975s: code 1: Not a number ""


Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

-26.919s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-26.919s: Failed. Falling back to ghc-mod
-26.919s: running ghc-mod type,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,36,33 with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-26.883s: ghc-mod said: Not a number ""
-26.883s: ghc-mod said: 
-26.883s: ghc-mod said: Usage: ghc-mod type FILE LINE COL
-26.883s: ghc-mod said:   Get the type of the expression under (LINE,COL)
-26.878s: ghc-mod ended with code 1
-26.878s: code 1: Not a number ""

Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

-26.849s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-26.849s: Failed. Falling back to ghc-mod
-26.849s: running ghc-mod info,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,enabled with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-26.765s: ghc-mod said: Warning: Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead.
-26.268s: ghc-mod said: EXCEPTION: info:
-26.268s: ghc-mod said:                parse error (possibly incorrect indentation or mismatched brackets)
-26.254s: ghc-mod ended with code 0
-26.254s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-26.253s: PATH = .....AppData\Local\atom\bin
-26.253s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-26.253s: Failed. Falling back to ghc-mod
-26.253s: running ghc-mod type,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,37,35 with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-26.232s: ghc-mod said: Not a number ""
-26.232s: ghc-mod said: 
-26.232s: ghc-mod said: Usage: ghc-mod type FILE LINE COL
-26.232s: ghc-mod said:   Get the type of the expression under (LINE,COL)
-26.229s: ghc-mod ended with code 1
-26.229s: code 1: Not a number ""


Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

-26.143s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-26.143s: PATH = .....AppData\Local\atom\bin
-26.143s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-26.143s: Failed. Falling back to ghc-mod
-26.143s: running ghc-mod info,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,upstream with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-26.093s: ghc-mod said: Warning: Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead.
-25.641s: ghc-mod said: EXCEPTION: info:
-25.641s: ghc-mod said:                parse error (possibly incorrect indentation or mismatched brackets)
-25.627s: ghc-mod ended with code 0
-25.624s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-25.624s: PATH = .....AppData\Local\atom\bin
-25.624s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-25.624s: Failed. Falling back to ghc-mod
-25.624s: running ghc-mod type,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,36,35 with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-25.601s: ghc-mod said: Not a number ""
-25.601s: ghc-mod said: 
-25.601s: ghc-mod said: Usage: ghc-mod type FILE LINE COL
-25.601s: ghc-mod said:   Get the type of the expression under (LINE,COL)
-25.598s: ghc-mod ended with code 1
-25.598s: code 1: Not a number ""


Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

-0.543s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-0.542s: PATH = .....AppData\Local\atom\bin
-0.542s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-0.541s: Failed. Falling back to ghc-mod
-0.541s: running ghc-mod info,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,enabled with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-0.457s: ghc-mod said: Warning: Warning: 'dist/setup-config' exists, ignoring Stack and using cabal-install instead.
-0.036s: ghc-mod said: EXCEPTION: info:
-0.035s: ghc-mod said:                parse error (possibly incorrect indentation or mismatched brackets)
-0.023s: ghc-mod ended with code 0
-0.022s: getProcessOptions(F:\P\thridparty\M\Sharingan)
-0.022s: PATH = .....AppData\Local\atom\bin
-0.021s: Trying to run ghc-modi in F:\P\thridparty\M\Sharingan
-0.021s: Failed. Falling back to ghc-mod
-0.021s: running ghc-mod type,F:\P\thridparty\M\Sharingan\src\Yaml.hs,,37,35 with options.cwd = F:\P\thridparty\M\Sharingan,options.env = [object Object],options.encoding = utf-8
-0.003s: ghc-mod said: Not a number ""
-0.003s: ghc-mod said: 
-0.003s: ghc-mod said: Usage: ghc-mod type FILE LINE COL
-0.003s: ghc-mod said:   Get the type of the expression under (LINE,COL)
-0.001s: ghc-mod ended with code 1
0s: code 1: Not a number ""


Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)


code 1: Not a number ""


Usage: ghc-mod type FILE LINE COL
  Get the type of the expression under (LINE,COL)

    at module.exports.Util.mkError (file:///C:/Users/H/.atom/packages/haskell-ghc-mod/lib/util.coffee:97:15)
    at BufferedProcess.exit (file:///C:/Users/H/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.coffee:117:20)
    at triggerExitCallback (C:\Users\H\AppData\Local\atom\app-1.3.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\H\AppData\Local\atom\app-1.3.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "language-mustache",
      "archive-view",
      "autosave",
      "background-tips",
      "language-objective-c"
    ],
    "autoHideMenuBar": true
  },
  "haskell-ghc-mod": {
    "useLinter": true,
    "enableGhcModi": false,
    "onSaveCheck": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.5.5
haskell-pointfree, v0.1.3
haskell-unicode-snippets, v0.1.0
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
ionide-fsharp, vundefined
language-agda, v0.2.2
language-batch, v0.3.3
language-cmake, v0.1.4
language-fsharp, v0.8.4
language-haskell, v1.5.2
language-idris, v0.4.0
language-racket, v0.4.0
language-rust, v0.4.5
language-sweetjs, v0.2.0
linter-python-pep8, v0.2.0
minimap, v4.19.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Should be fixed in 1.5.6. If not, feel free to let me know.
