### ISSUE TITLE
Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. 1

### ISSUE THREAD

**Issue by xujingao13** [atom-haskell/haskell-ghc-mod#90]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.3
**System**: Ubuntu 14.04.3
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.7

### Stack Trace

Haskell-ghc-mod: ghc-mod failed to launch. It is probably missing or misconfigured. 1

```
At Error: Command failed: ghc-mod version
"version" not supported

ghc-mod version 3.1.4
Usage:
	 ghc-mod list [-g GHC_opt1 -g GHC_opt2 ...] [-l] [-d]
	 ghc-mod lang [-l]
	 ghc-mod flag [-l]
	 ghc-mod browse [-g GHC_opt1 -g GHC_opt2 ...] [-l] [-o] [-d] [-q] [-p package] <module> [<module> ...]
	 ghc-mod check [-g GHC_opt1 -g GHC_opt2 ...] <HaskellFiles...>
	 ghc-mod expand [-g GHC_opt1 -g GHC_opt2 ...] <HaskellFiles...>
	 ghc-mod debug [-g GHC_opt1 -g GHC_opt2 ...] <HaskellFile>
	 ghc-mod info [-g GHC_opt1 -g GHC_opt2 ...] <HaskellFile> <module> <expression>
	 ghc-mod type [-g GHC_opt1 -g GHC_opt2 ...] <HaskellFile> <module> <line-no> <column-no>
	 ghc-mod lint [-h opt] <HaskellFile>
	 ghc-mod boot
	 ghc-mod help

  -l             --tolisp              print as a list of Lisp
  -h hlintOpt    --hlintOpt=hlintOpt   hlint options
  -g ghcOpt      --ghcOpt=ghcOpt       GHC options
  -o             --operators           print operators, too
  -d             --detailed            print detailed info
  -q             --qualified           show qualified names
  -p package-id  --package=package-id  specify package of module
  -b sep         --boundary=sep        specify line separator (default is Nul string)


PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
path: undefined
Path: undefined

Error
    at /home/jingao/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:60:28
    at ChildProcess.exithandler (child_process.js:222:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
haskell-ghc-mod, v1.5.7
ide-haskell, v1.3.9
ide-haskell-repl, v0.0.17
language-haskell, v1.5.2

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Ghc-mod v. 3 is not supported. Please update.
12 янв. 2016 г. 5:34 пользователь "Fancy_ao" <notifications@github.com>
написал:
