### ISSUE TITLE
haskell-ghc-mod crash when saving a file

### ISSUE THREAD

**Issue by jgoux** [atom-haskell/haskell-ghc-mod#92]
1. Open a .hs file in a stack project (after stack setup + stack build)
2. Type `Ctrl + s`

My stack.yaml is the default, I just changed the resolver to match the last LTS : 
```yaml
# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-4.1

# Local packages, usually specified by relative directory name
packages:
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
```
I didn't touch the default my-project.cabal file.

**Atom Version**: 1.3.1
**System**: Ubuntu 15.04
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.7

### Stack Trace

Haskell-ghc-mod: ghc-mod command check failed with error code 1

```
At caps: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
URI: /home/jgx/Projects/bio-access/contentieux-haskell/src/Lib.hs
Args: 
message: ghc-mod: <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d

    (use -v for more information)

log:
-22.203s: getProcessOptions(undefined)
-22.203s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-21.595s: Lib created
-21.594s: Lib updating
-21.594s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-21.594s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-21.569s: Lib buffer is set
-21.564s: Prelude created
-21.564s: Prelude updating
-21.564s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-21.563s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-21.545s: Prelude moduleName mismatch: Lib != Prelude
-21.523s: Prelude moduleName mismatch: undefined != Prelude
-21.503s: Prelude moduleName mismatch: undefined != Prelude
-20.604s: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
-20.603s: getProcessOptions(undefined)
-20.603s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-20.602s: running /home/jgx/.local/bin/ghc-mod lang with options.cwd = undefined,options.env = [object Object],options.encoding = utf-8
-20.566s: getProcessOptions(undefined)
-20.566s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-20.566s: running /home/jgx/.local/bin/ghc-mod flag with options.cwd = undefined,options.env = [object Object],options.encoding = utf-8
-20.545s: running /home/jgx/.local/bin/ghc-mod browse,-d,Lib with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-20.51s: running /home/jgx/.local/bin/ghc-mod browse,-d,Prelude with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-15.737s: /home/jgx/.local/bin/ghc-mod ended with code 0
-15.639s: /home/jgx/.local/bin/ghc-mod ended with code 0
-15.355s: /home/jgx/.local/bin/ghc-mod ended with code 0
-15.355s: Lib updated
-15.283s: /home/jgx/.local/bin/ghc-mod ended with code 0
-15.245s: Prelude updated
-9.52s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell/src)
-9.52s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-8.319s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-8.293s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-8.282s: Trying to run ghc-modi in /home/jgx/Projects/bio-access/contentieux-haskell
-8.265s: Checking for ghc-modi in /home/jgx/Projects/bio-access/contentieux-haskell
-8.264s: Spawning new ghc-modi instance for /home/jgx/Projects/bio-access/contentieux-haskell with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-8.264s: Spawning new ghc-modi instance for /home/jgx/Projects/bio-access/contentieux-haskell with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-8.136s: Started interactive action block in /home/jgx/Projects/bio-access/contentieux-haskell
-8.135s: Running ghc-modi command info,src/Lib.hs,someFufssfnc
-6.471s: ghc-modi said: EXCEPTION: info:
-6.466s: ghc-modi said:                <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d
-6.466s: ghc-modi said:                    (use -v for more information)
-6.465s: Got response from ghc-modi:
Cannot show info
OK

-6.465s: Ended interactive action block in /home/jgx/Projects/bio-access/contentieux-haskell
-6.46s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-6.459s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-6.459s: Trying to run ghc-modi in /home/jgx/Projects/bio-access/contentieux-haskell
-6.459s: Checking for ghc-modi in /home/jgx/Projects/bio-access/contentieux-haskell
-6.452s: Found running ghc-modi instance for /home/jgx/Projects/bio-access/contentieux-haskell
-6.451s: Started interactive action block in /home/jgx/Projects/bio-access/contentieux-haskell
-6.451s: Running ghc-modi command type,src/Lib.hs,6,32
-6.233s: ghc-modi said: EXCEPTION: types:
-6.23s: ghc-modi said:            <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d
-6.226s: ghc-modi said:                (use -v for more information)
-6.225s: Got response from ghc-modi:
OK

-6.225s: Ended interactive action block in /home/jgx/Projects/bio-access/contentieux-haskell
-4.552s: Prelude created
-4.552s: Prelude updating
-4.552s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-4.552s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-4.545s: running /home/jgx/.local/bin/ghc-mod browse,-d,Prelude with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-4.531s: Prelude moduleName mismatch: Lib != Prelude
-4.53s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-4.53s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-3.264s: Prelude moduleName mismatch: undefined != Prelude
-3.264s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-3.264s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-2.37s: Prelude moduleName mismatch: undefined != Prelude
-2.333s: /home/jgx/.local/bin/ghc-mod ended with code 0
-2.332s: Prelude updated
-2.292s: ghc-modi said: ghc-mod: <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d
-2.292s: ghc-modi said:     (use -v for more information)
-2.264s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-2.264s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-2.264s: running /home/jgx/.local/bin/ghc-mod check,/home/jgx/Projects/bio-access/contentieux-haskell/src/Lib.hs with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-2.247s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-2.247s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-2.247s: running /home/jgx/.local/bin/ghc-mod lint,/home/jgx/Projects/bio-access/contentieux-haskell/src/Lib.hs with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-2.239s: Lib did-save triggered
-2.239s: Lib updating
-2.239s: getProcessOptions(/home/jgx/Projects/bio-access/contentieux-haskell)
-2.238s: PATH = /home/jgx/.stack/programs/x86_64-linux/ghc-7.10.2/bin:/home/jgx/.local/bin:/home/jgx/.nvm/versions/node/v5.3.0/bin:/home/jgx/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/jgx/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
-2.236s: running /home/jgx/.local/bin/ghc-mod browse,-d,Lib with options.cwd = /home/jgx/Projects/bio-access/contentieux-haskell,options.env = [object Object],options.encoding = utf-8
-0.004s: ghc-mod said: ghc-mod: <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d
-0.001s: ghc-mod said:     (use -v for more information)
-0.001s: /home/jgx/.local/bin/ghc-mod ended with code 1
0s: code 1: ghc-mod: <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d

    (use -v for more information)


code 1: ghc-mod: <command line>: cannot satisfy -package-id base-4.8.2.0-0d6d1084fbc041e1cded9228e80e264d

    (use -v for more information)

    at module.exports.Util.mkError (/home/jgx/.atom/packages/haskell-ghc-mod/lib/util.coffee:97:15)
    at BufferedProcess.exit (/home/jgx/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process-real.coffee:117:20)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -0:07.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.4.0 ide-haskell:prettify-file (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModiPath": "/home/jgx/.local/bin/ghc-modi",
    "ghcModPath": "/home/jgx/.local/bin/ghc-mod"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
file-icons, v1.6.13
haskell-ghc-mod, v1.5.7
highlight-line, v0.11.0
highlight-selected, v0.11.1
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.2
language-purescript, v0.6.1
linter, v1.11.3
monokai, v0.18.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Mixing ghc versions is not supported at the moment. You need to have a
separate installation of ghc-mod for each ghc version. See also
https://github.com/DanielG/ghc-mod/issues/615
12 янв. 2016 г. 12:48 пользователь "Julien Goux" <notifications@github.com>
написал:

**Comment by lierdakil** [comment]
Also see https://github.com/atom-haskell/haskell-ghc-mod/wiki/Using-with-stack.

**Comment by lierdakil** [comment]
Closing due to age
