### ISSUE TITLE
Uncaught TypeError: editor.getBuffer is not a function

### ISSUE THREAD

**Issue by lwdye** [atom-haskell/haskell-ghc-mod#94]
Updated to 1.5.8.

**Atom Version**: 1.3.3
**System**: Mac OS X 10.10.5
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.5.8

### Stack Trace

Uncaught TypeError: editor.getBuffer is not a function

```
At /Users/lwdye/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:213

TypeError: editor.getBuffer is not a function
    at GhcModiProcess.module.exports.GhcModiProcess.getInfoInBuffer (/Users/lwdye/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:213:21)
    at GhcModiProcess.getInfoInBuffer (/Users/lwdye/.atom/packages/haskell-ghc-mod/lib/ghc-mod/ghc-modi-process.coffee:1:1)
    at /Users/lwdye/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:114:7
    at infoTypeTooltip (/Users/lwdye/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:118:7)
    at /Users/lwdye/.atom/packages/haskell-ghc-mod/lib/haskell-ghc-mod.coffee:208:11
    at _this.showTooltip.tooltip (/Users/lwdye/.atom/packages/ide-haskell/lib/upi.coffee:115:30)
    at /Users/lwdye/.atom/packages/ide-haskell/lib/upi.coffee:131:7
    at UPIInstance.withEventRange (/Users/lwdye/.atom/packages/ide-haskell/lib/upi.coffee:208:5)
    at UPIInstance.showTooltip (/Users/lwdye/.atom/packages/ide-haskell/lib/upi.coffee:130:6)
    at /Users/lwdye/.atom/packages/ide-haskell/lib/upi.coffee:111:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/lwdye/.atom/packages/ide-haskell/lib/plugin-manager.coffee:73:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at EditorControl.shouldShowTooltip (/Users/lwdye/.atom/packages/ide-haskell/lib/editor-control.coffee:129:16)
    at /Users/lwdye/.atom/packages/ide-haskell/lib/editor-control.coffee:53:42
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "script",
      "ide-haskell-cabal"
    ]
  },
  "haskell-ghc-mod": {
    "ghcModPath": "/Users/lwdye/.local/bin/ghc-mod",
    "ghcModiPath": "/Users/lwdye/.local/bin/ghc-modi"
  }
}
```

### Installed Packages

```coffee
# User
atom-json-editor, v0.4.1
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.5.8
ide-haskell, v1.3.9
language-haskell, v1.5.2
language-java, v0.17.0
language-mathematica, v0.1.0
react, v0.12.10

# Dev
No dev packages
```

**Comment by kolbebe** [comment]
Same issue

**Comment by lierdakil** [comment]
Sorry about that.

**Comment by lwdye** [comment]
No worries.  Thanks for the quick response.
