### ISSUE TITLE
Haskell-ghc-mod: ghc-mod interactive command info failed with error ghc-modi crashed

### ISSUE THREAD

**Issue by tj-89** [atom-haskell/haskell-ghc-mod#96]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [haskell-ghc-mod](https://github.com/atom-haskell/haskell-ghc-mod) package, v1.6.3

### Stack Trace

Haskell-ghc-mod: ghc-mod interactive command info failed with error ghc-modi crashed

```
At caps: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
URI: /Users/todd.irving/Documents/sware/haskell/fizzbuzz/fb.hs
Args: return
message: 
log:
-3.981s: getProcessOptions(/Users/todd.irving/Documents/sware/haskell/fizzbuzz)
-3.975s: PATH = /Users/todd.irving/Library/Haskell/bin/hlint:$HOME/Library/Haskell/bin:$PATH:/usr/local/sbin:$PATH:/usr/bin:/bin:/usr/sbin:/sbin
-3.844s: Main created
-3.844s: Main updating
-3.842s: Main buffer is set
-3.842s: Prelude created
-3.842s: Prelude updating
-3.84s: Prelude moduleName mismatch: undefined != Prelude
-3.837s: Prelude moduleName mismatch: Main != Prelude
-3.823s: {"version":[5,4,0,0],"legacyInteractive":true,"fileMap":true,"rootExec":true,"quoteArgs":false}
-3.821s: running /Users/todd.irving/Library/Haskell/bin/ghc-mod lang with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8
-3.813s: running /Users/todd.irving/Library/Haskell/bin/ghc-mod flag with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8
-3.81s: running /Users/todd.irving/Library/Haskell/bin/ghc-mod browse,-d,Main with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8
-3.808s: running /Users/todd.irving/Library/Haskell/bin/ghc-mod browse,-d,Prelude with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8
-3.742s: ghc-mod said: cabal-helper-wrapper: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
-3.742s: ghc-mod said: cabal-helper-wrapper: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
-3.742s: ghc-mod said: cabal-helper-wrapper: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
-3.742s: ghc-mod said: cabal-helper-wrapper: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
-3.7s: /Users/todd.irving/Library/Haskell/bin/ghc-mod ended with code 0
-3.699s: Main updated
-3.699s: /Users/todd.irving/Library/Haskell/bin/ghc-mod ended with code 0
-3.699s: Prelude updated
-3.699s: /Users/todd.irving/Library/Haskell/bin/ghc-mod ended with code 0
-3.699s: /Users/todd.irving/Library/Haskell/bin/ghc-mod ended with code 0
-0.052s: Trying to run ghc-modi in /Users/todd.irving/Documents/sware/haskell/fizzbuzz
-0.052s: Checking for ghc-modi in /Users/todd.irving/Documents/sware/haskell/fizzbuzz
-0.052s: Spawning new ghc-modi instance for /Users/todd.irving/Documents/sware/haskell/fizzbuzz with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8,options.timeout = 5000
-0.052s: Spawning new ghc-modi instance for /Users/todd.irving/Documents/sware/haskell/fizzbuzz with options.cwd = /Users/todd.irving/Documents/sware/haskell/fizzbuzz,options.env = [object Object],options.encoding = utf-8,options.timeout = 5000
-0.04s: Started interactive action block in /Users/todd.irving/Documents/sware/haskell/fizzbuzz
-0.04s: Running ghc-modi command info,fb.hs,return
-0.005s: ghc-modi said: cabal-helper-wrapper: ghc: readCreateProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
-0.004s: ghc-modi said: ghc-mod: readCreateProcess: /Users/todd.irving/Library/Haskell/libexec/cabal-helper-wrapper "/Users/todd.irving/Documents/sware/haskell/fizzbuzz" "/Users/todd.irving/Documents/sware/haskell/fizzbuzz/dist" (exit 1): failed
-0.001s: ghc-modi for /Users/todd.irving/Documents/sware/haskell/fizzbuzz ended with 1
-0.001s: ghc-modi for /Users/todd.irving/Documents/sware/haskell/fizzbuzz ended with 1
0s: Running ghc-modi command unmap-file,fb.hs
0s: ghc-modi crashed

ghc-modi crashed
    at module.exports.Util.mkError (/Users/todd.irving/.atom/packages/haskell-ghc-mod/lib/util.coffee:154:15)
    at ChildProcess.exitCallback (/Users/todd.irving/.atom/packages/haskell-ghc-mod/lib/ghc-mod/interactive-process.coffee:76:20)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
     -0:34.2.0 application:hide (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "ide-haskell"
    ],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "haskell-ghc-mod": {
    "additionalPathDirectories": [
      "/Users/todd.irving/Library/Haskell/bin/hlint",
      "$HOME/Library/Haskell/bin:$PATH",
      "/usr/local/sbin:$PATH"
    ],
    "ghcModPath": "/Users/todd.irving/Library/Haskell/bin/ghc-mod",
    "ghcModiPath": "/Users/todd.irving/Library/Haskell/bin/ghc-modi",
    "useLinter": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.6.2
haskell-ghc-mod, v1.6.3
ide-haskell, v1.3.9
ide-haskell-cabal, v1.0.0
language-haskell, v1.5.2
language-smarty, v1.4.0

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Shell expansion is NOT supported in 'Additional Path Directories'. Run
'echo PATH' in terminal, replace colons with commas and put result into APD
setting.

Also, '.../bin/hlint' is not a directory. This can lead to problems. Remove
'/hlint' part.
14 янв. 2016 г. 21:48 пользователь "TJ Irving" <notifications@github.com>
написал:

**Comment by tj-89** [comment]
Solved it thanks

**Comment by mukeshsoni** [comment]
@tj-89  where do i find the config file?
